### PR TITLE
force install the custom version of ipyleaflet

### PR DESCRIPTION
**Pull request by 12rambau**
As mentioned in https://github.com/12rambau/sepal_ui/pull/902, we cannot change the version of ipyleaflet used in sepal_ui to a branch. on the other hand it's perfectly possible to force intall it from here as we do for earthengine. 

As long tas the applications are still using a loose pin on ipylaflet (which shoould be the case) it will work.

Mentioning @dfguerrerom for the follow-up

### CODE REVIEW

**Comment by dfguerrerom** [comment]
@12rambau can you change your PR to `jellyfish` branch?

**Comment by 12rambau** [comment]
done

**Comment by dfguerrerom** [comment]
I would put this PR on hold until we decide tomorrow if it's better to use the `wheel` (too speed up the build) or the repo.

**Comment by dfguerrerom** [comment]
no longer needed, check https://github.com/jupyter-widgets/ipyleaflet/pull/1146

**Pull request closed without merging**
